# Site settings
title:       "SortMan&trade;"
description: > # this means to ignore newlines until "baseurl:"
             A webapp to sort people in teams.
baseurl:     "" # the subpath of your site, e.g. /blog
#url:         "http://sortman.tk" # the base hostname & protocol for your site

# User names
twitter_user: octopusinvitro
git_user:     me-stevens

# Build settings
exclude: [.gitignore, exclude, js/jasmine/lib, js/jasmine/spec, js/jasmine/SpecRunner.html, README.md, LICENSE.txt, .editorconfig]
sass:
  style: compressed
future:  true